name: tz
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  http: ^1.1.0
  dartz: ^0.10.1
  get_it: ^7.6.4
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  mask_text_input_formatter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - lib/assets/icon/
    - lib/assets/fonts/
  fonts:

    - family: SF-Pro-Display
      fonts:
        - asset: lib/assets/fonts/SF-Pro-Display-Black.otf
        - asset: lib/assets/fonts/SF-Pro-Display-BlackItalic.otf
        - asset: lib/assets/fonts/SF-Pro-Display-Bold.otf
        - asset: lib/assets/fonts/SF-Pro-Display-BoldItalic.otf
        - asset: lib/assets/fonts/SF-Pro-Display-Heavy.otf
        - asset: lib/assets/fonts/SF-Pro-Display-HeavyItalic.otf
        - asset: lib/assets/fonts/SF-Pro-Display-Light.otf
        - asset: lib/assets/fonts/SF-Pro-Display-LightItalic.otf
        - asset: lib/assets/fonts/SF-Pro-Display-Medium.otf
        - asset: lib/assets/fonts/SF-Pro-Display-MediumItalic.otf
        - asset: lib/assets/fonts/SF-Pro-Display-Regular.otf
        - asset: lib/assets/fonts/SF-Pro-Display-RegularItalic.otf
        - asset: lib/assets/fonts/SF-Pro-Display-Semibold.otf
        - asset: lib/assets/fonts/SF-Pro-Display-SemiboldItalic.otf
        - asset: lib/assets/fonts/SF-Pro-Display-Thin.otf
        - asset: lib/assets/fonts/SF-Pro-Display-ThinItalic.otf
        - asset: lib/assets/fonts/SF-Pro-Display-Ultralight.otf
        - asset: lib/assets/fonts/SF-Pro-Display-UltralightItalic.otf
    # - family: Schyler
    #   fonts:
    #     - asset: fonts/Schyler-Regular.ttf
    #     - asset: fonts/Schyler-Italic.ttf

  #         style: italic
  #   - family: Trajan Pro
      # fonts:
      #   - asset: fonts/TrajanPro.ttf
      #   - asset: fonts/TrajanPro_Bold.ttf
      #     weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
